spring.application.name=arc1
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.bdoaznoajsllanqvejbo&password=AmketteNatural@1
spring.datasource.username=postgres
spring.datasource.password=AmketteNatural@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

