package com.arcus.arc1.AiWorkoutPlan;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Stores the AI-generated personalised workout plan for a user.
 *
 * One row = one exercise assigned by ChatGPT for a specific day.
 * The plan is generated once (on profile creation) and reused every time the
 * user generates a workout for that day.  It can be regenerated by calling
 * POST /ai-plan/generate?userId={userId} (e.g. after the user updates their profile).
 */
@Entity
@Table(name = "ai_workout_plan",
        indexes = @Index(name = "idx_ai_plan_user_day", columnList = "user_id, day_number"))
public class AiWorkoutPlanEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The Arcus user this plan belongs to. */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    /** Which workout day this exercise belongs to (1-based, matches workout_template day_number). */
    @Column(name = "day_number", nullable = false)
    private Integer dayNumber;

    /** Human-readable name for the day, e.g. "Push – Chest & Triceps". */
    @Column(name = "day_name", length = 255)
    private String dayName;

    /** FK → exercise_library.id — the specific exercise ChatGPT chose for this slot. */
    @Column(name = "exercise_library_id")
    private Long exerciseLibraryId;

    /** Primary muscle group for this exercise slot (denormalised for quick lookups). */
    @Column(name = "muscle_group", length = 100)
    private String muscleGroup;

    /** ChatGPT-recommended number of sets (overrides exercise_library default when present). */
    @Column(name = "sets")
    private Integer sets;

    /** ChatGPT-recommended minimum reps per set. */
    @Column(name = "rep_min")
    private Integer repMin;

    /** ChatGPT-recommended maximum reps per set. */
    @Column(name = "rep_max")
    private Integer repMax;

    /** When this plan was generated. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) createdAt = LocalDateTime.now();
    }

    public AiWorkoutPlanEntity() {}

    // ── Getters / Setters ─────────────────────────────────────────────────────

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Long getUserId() { return userId; }
    public void setUserId(Long userId) { this.userId = userId; }

    public Integer getDayNumber() { return dayNumber; }
    public void setDayNumber(Integer dayNumber) { this.dayNumber = dayNumber; }

    public String getDayName() { return dayName; }
    public void setDayName(String dayName) { this.dayName = dayName; }

    public Long getExerciseLibraryId() { return exerciseLibraryId; }
    public void setExerciseLibraryId(Long exerciseLibraryId) { this.exerciseLibraryId = exerciseLibraryId; }

    public String getMuscleGroup() { return muscleGroup; }
    public void setMuscleGroup(String muscleGroup) { this.muscleGroup = muscleGroup; }

    public Integer getSets() { return sets; }
    public void setSets(Integer sets) { this.sets = sets; }

    public Integer getRepMin() { return repMin; }
    public void setRepMin(Integer repMin) { this.repMin = repMin; }

    public Integer getRepMax() { return repMax; }
    public void setRepMax(Integer repMax) { this.repMax = repMax; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}

